# -*- coding: utf-8 -*-
"""100 题路由分类基准测试集。

题目来源: StackOverflow 高频问题 / GitHub Issues 真实排障 / 各领域经典面试题,
覆盖 7 大领域: java / oracle / mysql / kubernetes / linux / network / generic(含 日常/前端/科学)。

每项: (期望路由, 问题)
"""
BENCH_100 = [
    # ---- Java / JVM (15) ----
    ("java", "Java 8 的 Stream API 中 reduce 和 collect 有什么区别？"),
    ("java", "Spring Boot 启动时 Bean 循环依赖怎么解决？"),
    ("java", "JVM 堆内存溢出 OutOfMemoryError 怎么排查？"),
    ("java", "ConcurrentHashMap 在 JDK 8 中为什么改成 CAS + synchronized？"),
    ("java", "ThreadLocal 内存泄漏的原因是什么？"),
    ("java", "Maven 依赖冲突怎么解决？"),
    ("java", "G1 垃圾收集器相比 CMS 有什么优势？"),
    ("java", "Java 中 == 和 equals 的区别？"),
    ("java", "MyBatis 一级缓存和二级缓存有什么区别？"),
    ("java", "Spring 事务传播机制有哪些？"),
    ("java", "JVM 如何判断对象可以被回收？"),
    ("java", "Java 线程池参数怎么设置？"),
    ("java", "Lambda 表达式捕获外部变量为什么要求是 effectively final？"),
    ("java", "Spring Cloud 服务熔断降级怎么实现？"),
    ("java", "Java 反射性能差的原因及替代方案？"),

    # ---- Oracle (15) ----
    ("oracle", "Oracle RAC 两个节点负载不均衡怎么办？"),
    ("oracle", "Oracle 数据库表空间满了怎么处理？"),
    ("oracle", "Oracle 执行计划里全表扫描怎么优化？"),
    ("oracle", "Oracle 11g 和 19c 的归档日志管理有什么区别？"),
    ("oracle", "Oracle Data Guard 主备切换 failover 流程？"),
    ("oracle", "Oracle 中 NULL 为什么排序默认排最后？"),
    ("oracle", "Oracle 闪回查询 flashback query 的使用场景？"),
    ("oracle", "Oracle AWR 报告中 Top Event 怎么分析？"),
    ("oracle", "Oracle 分区表按时间分区的好处？"),
    ("oracle", "Oracle 中游标泄漏会导致什么问题？"),
    ("oracle", "Oracle SGA 和 PGA 的区别？"),
    ("oracle", "Oracle 锁等待和阻塞怎么定位？"),
    ("oracle", "Oracle RMAN 增量备份策略怎么设计？"),
    ("oracle", "Oracle 中 v$session 和 v$process 的关系？"),
    ("oracle", "Oracle 表重建时为什么要在线重定义？"),

    # ---- MySQL (12) ----
    ("mysql", "MySQL 索引为什么用 B+ 树不用红黑树？"),
    ("mysql", "MySQL InnoDB 和 MyISAM 有什么区别？"),
    ("mysql", "MySQL 慢查询日志怎么开启和分析？"),
    ("mysql", "MySQL 主从复制延迟的原因有哪些？"),
    ("mysql", "MySQL 死锁怎么定位和解决？"),
    ("mysql", "MySQL 联合索引的最左前缀原则是什么？"),
    ("mysql", "MySQL 大表加字段为什么会锁表？"),
    ("mysql", "MySQL binlog 三种格式有什么区别？"),
    ("mysql", "MySQL 幻读和 MVCC 有什么关系？"),
    ("mysql", "MySQL 分库分表后跨库查询怎么办？"),
    ("mysql", "MySQL buffer pool 命中率低怎么调优？"),
    ("mysql", "MySQL 半同步复制和异步复制有什么区别？"),

    # ---- Kubernetes (15) ----
    ("kubernetes", "Pod 一直 CrashLoopBackOff 怎么排查？"),
    ("kubernetes", "K8s Deployment 滚动更新卡住怎么办？"),
    ("kubernetes", "Service 无法访问 Pod 的排查步骤？"),
    ("kubernetes", "K8s 里 Node 显示 NotReady 怎么处理？"),
    ("kubernetes", "Pod 调度不到节点上的原因有哪些？"),
    ("kubernetes", "K8s PV 和 PVC 绑定失败的常见原因？"),
    ("kubernetes", "Ingress 配置后 404 怎么排查？"),
    ("kubernetes", "K8s 中污点和容忍度的使用场景？"),
    ("kubernetes", "K8s HPA 自动扩缩容不生效的原因？"),
    ("kubernetes", "Etcd 性能下降怎么诊断？"),
    ("kubernetes", "K8s 里 ConfigMap 更新后 Pod 为什么不生效？"),
    ("kubernetes", "K8s 网络插件 Calico 和 Flannel 的区别？"),
    ("kubernetes", "Pod 里容器 OOMKilled 怎么定位是哪个进程？"),
    ("kubernetes", "K8s 集群证书过期怎么处理？"),
    ("kubernetes", "kubelet 报错 failed to get sandbox image 怎么解决？"),

    # ---- Linux (10) ----
    ("linux", "服务器 CPU 100% 怎么定位是哪个进程？"),
    ("linux", "Linux 磁盘空间满了但 df 显示还有空间？"),
    ("linux", "Linux 中僵尸进程怎么清理？"),
    ("linux", "Linux 下端口被占用怎么找出进程？"),
    ("linux", "systemd 服务启动失败怎么排查？"),
    ("linux", "Linux 内存被缓存占用过高需要清理吗？"),
    ("linux", "Linux 文件句柄耗尽 too many open files 怎么解决？"),
    ("linux", "Linux 下软链接和硬链接的区别？"),
    ("linux", "Linux 定时任务 crontab 不执行怎么排查？"),
    ("linux", "Linux 负载 load average 高但 CPU 空闲怎么回事？"),

    # ---- Network (10) ----
    ("network", "两台服务器 ping 不通怎么排查？"),
    ("network", "TCP 三次握手和四次挥手的过程？"),
    ("network", "nginx 502 Bad Gateway 怎么排查？"),
    ("network", "DNS 解析慢怎么定位？"),
    ("network", "TCP TIME_WAIT 过多会有什么影响？"),
    ("network", "负载均衡算法有哪些？"),
    ("network", "HTTPS 握手过程是怎样的？"),
    ("network", "TCP 和 UDP 有什么区别？"),
    ("network", "网络丢包怎么用 tcpdump 定位？"),
    ("network", "反向代理和正向代理的区别？"),

    # ---- Generic - 日常/前端/科学 (23) ----
    ("generic", "今天中午吃什么好？"),
    ("generic", "帮我写一段产品介绍文案。"),
    ("generic", "前端用 Tailwind 怎么做玻璃拟态卡片？"),
    ("generic", "为什么天空是蓝色的？"),
    ("generic", "什么是区块链？"),
    ("generic", "帮我拟一个会议邀请邮件。"),
    ("generic", "React 和 Vue 怎么选择？"),
    ("generic", "CSS 里 flex 布局怎么居中？"),
    ("generic", "JavaScript 闭包是什么？"),
    ("generic", "什么是光合作用？"),
    ("generic", "帮我翻译这句话成英文。"),
    ("generic", "量子计算的基本原理是什么？"),
    ("generic", "UI 设计里留白的重要性？"),
    ("generic", "HTML 语义化标签有什么好处？"),
    ("generic", "黑洞是怎么形成的？"),
    ("generic", "帮我写一首关于秋天的诗。"),
    ("generic", "什么是人工智能？"),
    ("generic", "Axios 和 fetch 怎么选？"),
    ("generic", "Vue3 的 Composition API 和 Options API 区别？"),
    ("generic", "什么是相对论？"),
    ("generic", "前端性能优化有哪些手段？"),
    ("generic", "帮我总结这篇文章的要点。"),
    ("generic", "什么是暗物质？"),
]
